services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "4242:80"
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
